### PR TITLE
New Interface: "extract_multiple_solutions" method for all reductions

### PR DESCRIPTION
**Pull request by SciCodePhy**

### CODE REVIEW

**Comment by SciCodePhy** [comment]
Conclusion: 
- Only for "SAT=>Independent Set" reduction, "extract_multiple_solutions" is non-trivially inequivalent with "extract_solution". "extract_multiple_solutions" in other reductions are trivial.

**Comment by GiggleLiu** [comment]
Thanks for the pr, but you do not have to write so many functions. You can make use of multiple dispatch: https://docs.julialang.org/en/v1/manual/methods/

Also, can you please show a practical using case to support the added interface?

**Comment by SciCodePhy** [comment]
> Thanks for the pr, but you do not have to write so many functions. You can make use of multiple dispatch: https://docs.julialang.org/en/v1/manual/methods/
> 
> Also, can you please show a practical using case to support the added interface?

The "extract_multiple_solutions" interface is especially useful for the reductions where instances don't follow 1-1 mapping, such as "SAT=>Independent Set" reduction. It can give return a complete set of solutions when the user input a set of solutions. I believe this would be useful for some scenarios.

**Review by GiggleLiu — APPROVED** [review]
Looks much better after the change.

**Pull request merged**
