### PR TITLE
Add a new type: QUBO

### PR DESCRIPTION
**Pull request by SciCodePhy**
Question: Can we define QUBO on a graph?

### CODE REVIEW

**Review by GiggleLiu — APPROVED** [review]

**Comment by GiggleLiu** [comment]
Matrix can be regarded as the adjacency matrix of a weighted graph.

**Comment by hmyuuu** [comment]
> Can we define QUBO on a graph?
I think we can wrap on like [SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl), I’m happy to help with the implementation if needed. 
Ref. 
[ ref1 ](https://docs.dwavesys.com/docs/latest/c_gs_3.html#minor-embedding) [ref2](https://openqaoa.entropicalabs.com/problems/what-is-a-qubo/#from-qubos-to-qaoa)

**Comment by SciCodePhy** [comment]
> Matrix can be regarded as the adjacency matrix of a weighted graph.



> > Can we define QUBO on a graph?
> 
> I think we can wrap on like [SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl), I’m happy to help with the implementation if needed. Ref. [ ref1 ](https://docs.dwavesys.com/docs/latest/c_gs_3.html#minor-embedding) [ref2](https://openqaoa.entropicalabs.com/problems/what-is-a-qubo/#from-qubos-to-qaoa)

Thanks for the suggestions! I add a function which can construct QUBO from a simple graph. The inputs are: a simple graph and a weights vector #55 . 

Maybe we can further construct QUBO directly from simple weighted graph as suggested by @hmyuuu (to make the interface more robust?). But I am not sure whether this would be redundant.

**Comment by GiggleLiu** [comment]
[SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl) seems to be poorly maintained.

**Comment by SciCodePhy** [comment]
> [SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl) seems to be poorly maintained, making it unlikely to be a depenedency.

No problem. Then I think the interface for simple graph is enough.

**Pull request merged**
